// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avablnfllwcsvjoqbzyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2YWJsbmZsbHdjc3Zqb3FienlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTU5OTYsImV4cCI6MjA2MTQ5MTk5Nn0.FmJ5_-ST3yK_UqHeu2zp8XUaX1kMqDnmmayO_Cv-gNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);